export const PRODUCT_LIST_REQ = "PRODUCT_LIST_REQ"
export const PRODUCT_LIST_REQ_SUCCESS = "PRODUCT_LIST_REQ_SUCCESS"
export const PRODUCT_LIST_REQ_FAIL = "PRODUCT_LIST_REQ_FAIL"

export const PRODUCT_DEATIL_REQ = "PRODUCT_DEATIL_REQ"
export const PRODUCT_DEATIL_REQ_SUCCESS = "PRODUCT_DEATIL_REQ_SUCCESS"
export const PRODUCT_DEATIL_REQ_FAIL = "PRODUCT_DEATIL_REQ_FAIL"